name: APC
description: A simple plugin to manage chat with LuckPerms!
version: 1.0
main: com.xthesilent.apc.APC
author: XTHESilent
api-version: 1.13
depend: [AquaPerms]
softdepend: [PlaceholderAPI]
commands:
  apc:
    description: Reload the configuration.
    permission: apc.reload
    usage: "Usage: /apc reload"
